# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-12-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='articletotag',
            options={'verbose_name_plural': '文章与标签的对应表'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '博客表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '分章分类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='upanddown',
            options={'verbose_name_plural': '点赞点踩表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='bolg',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='bolg',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='bolg',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
