# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-12-01 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20221201_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
