# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-12-05 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20221201_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upanddown',
            name='is_down',
        ),
    ]
